# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stormtrooper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stormtrooper
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Google/Analytics'

  target 'StormtrooperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StormtrooperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
