# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TogetherStream' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TogetherStream
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Google/Analytics'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'youtube-ios-player-helper'
  pod 'ALTextInputBar'

  target 'TogetherStreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TogetherStreamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
